2016-11-22 15:37:02  [ pool-1-thread-1:11034 ] - [ ERROR ]  查询微信订单验证签名失败！！！
2016-11-22 15:43:30  [ pool-1-thread-1:27290 ] - [ ERROR ]  查询微信订单验证签名失败！！！
2016-11-22 15:55:30  [ pool-1-thread-1:6046 ] - [ ERROR ]  查询微信订单验证签名失败！！！
2016-11-22 15:56:00  [ pool-1-thread-1:35676 ] - [ ERROR ]  查询微信订单验证签名失败！！！
2016-11-22 15:56:30  [ pool-1-thread-1:65747 ] - [ ERROR ]  查询微信订单验证签名失败！！！
2016-11-22 15:57:00  [ pool-1-thread-1:95700 ] - [ ERROR ]  查询微信订单验证签名失败！！！
2016-11-22 16:01:30  [ pool-1-thread-1:4939 ] - [ ERROR ]  查询微信订单验证签名失败！！！
2016-11-22 16:04:30  [ pool-1-thread-1:52405 ] - [ ERROR ]  Unexpected error occurred in scheduled task.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.cmpay.weixin.service.impl.PaymentServiceImpl.QueryWXOrder(PaymentServiceImpl.java:337)
	at com.cmpay.service.quartz.scheduler.WeixinTask.wxOrderQuery(WeixinTask.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2016-11-22 16:05:00  [ pool-1-thread-1:82408 ] - [ ERROR ]  Unexpected error occurred in scheduled task.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.cmpay.weixin.service.impl.PaymentServiceImpl.QueryWXOrder(PaymentServiceImpl.java:337)
	at com.cmpay.service.quartz.scheduler.WeixinTask.wxOrderQuery(WeixinTask.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
